name: Go Build and Test
run-name: Go Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    name: "Build on Linux"
    runs-on: [linux]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Linux
        env:
          GOOS: "linux"
          GOARCH: "amd64"
          CGO_ENABLED: "0"
          GONOSUMDB": "*"
        run: go build -v -o /tmp/runner.exe ./cmd/util/runner/run.go

      - name: Test
        run: "go test -v ./cmd/util/runner"

  windows:
    name: "Build on Windows"
    runs-on: [windows]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Windows
        env:
          GOOS: "windows"
          GOARCH: "amd64"
          GONOSUMDB": "*"

        run: go build -v -o /tmp/runner.exe ./cmd/util/runner/run.go

      - name: Test
        run: "go test -v ./cmd/util/runner"
